services:
  # ... db service ...

  api:
    image: ghcr.io/femavibes/feedmaster/api:latest
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      # NEW: Add DATABASE_URL here!
      DATABASE_URL: ${DATABASE_URL}
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
    depends_on:
      - db

  aggregator_worker:
    image: ghcr.io/femavibes/feedmaster/api:latest # Assuming this image also contains the worker code
    restart: unless-stopped
    command: python backend/aggregator_worker.py
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      # NEW: Add DATABASE_URL here!
      DATABASE_URL: ${DATABASE_URL}
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
      WORKER_POLLING_INTERVAL_SECONDS: ${WORKER_POLLING_INTERVAL_SECONDS}
      AGGREGATION_INTERVAL_MINUTES: ${AGGREGATION_INTERVAL_MINUTES}
      PROMINENT_DID_REFRESH_INTERVAL_MINUTES: ${PROMINENT_DID_REFRESH_INTERVAL_MINUTES}
    depends_on:
      - db

volumes:
  pgdata: