# docker-compose.yml (corrected section for api and aggregator_worker)

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: feedmaster_db
      POSTGRES_USER: datamaster
      POSTGRES_PASSWORD: 0437663470b59957dbd7ed2164500bd3dc41dc847b27a0cd7363280ecda78481
    healthcheck:
      # IMPORTANT: Use $$ to escape the $ for shell variable expansion
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"] # <-- FIX HERE
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    # Change 'image:' to 'build:' to build locally
    build: . # <-- FIX HERE: This tells Docker Compose to build the image from the Dockerfile in the current directory
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
    depends_on: # <-- FIX HERE: Add condition: service_healthy
      db:
        condition: service_healthy

  aggregator_worker:
    # Change 'image:' to 'build:' to build locally
    build: . # <-- FIX HERE
    restart: unless-stopped
    command: python -m backend.aggregator_worker
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
      WORKER_POLLING_INTERVAL_SECONDS: ${WORKER_POLLING_INTERVAL_SECONDS}
      AGGREGATION_INTERVAL_MINUTES: ${AGGREGATION_INTERVAL_MINUTES}
      PROMINENT_DID_REFRESH_INTERVAL_MINUTES: ${PROMINENT_DID_REFRESH_INTERVAL_MINUTES}
    depends_on: # <-- FIX HERE: Add condition: service_healthy
      db:
        condition: service_healthy

volumes:
  pgdata: