# No 'version: X.Y' at the top - it's obsolete and can be removed.

services:
  db:
    image: postgres:15-alpine # Use a lightweight PostgreSQL image
    restart: always # Always restart the database service if it fails
    environment:
      POSTGRES_DB: feedmaster_db # Database name
      POSTGRES_USER: datamaster # Database user
      POSTGRES_PASSWORD: 0437663470b59957dbd7ed2164500bd3dc41dc847b27a0cd7363280ecda78481 # Database password (MAKE SURE THESE MATCH YOUR .env)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Give it a bit of time to start before checking
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data to a named volume
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432

  api:
    image: ghcr.io/femavibes/feedmaster/api:latest
    restart: unless-stopped
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL} # Crucial for database.py
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
    depends_on:
      - db

  aggregator_worker:
    image: ghcr.io/femavibes/feedmaster/api:latest # Assuming this image also contains the worker code
    restart: unless-stopped
    command: python -m backend.aggregator_worker # This command might need adjustment if relative imports still fail after this.
    volumes:
      - ./config:/app/config
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATABASE_URL: ${DATABASE_URL} # Crucial for database.py
      BLUESKY_API_BASE_URL: ${BLUESKY_API_BASE_URL}
      CONFIG_DIR: /app/config
      WORKER_POLLING_INTERVAL_SECONDS: ${WORKER_POLLING_INTERVAL_SECONDS}
      AGGREGATION_INTERVAL_MINUTES: ${AGGREGATION_INTERVAL_MINUTES}
      PROMINENT_DID_REFRESH_INTERVAL_MINUTES: ${PROMINENT_DID_REFRESH_INTERVAL_MINUTES}
    depends_on:
      - db

volumes:
  pgdata: # Define the named volume for PostgreSQL data persistence