"""Replace single image fields with images JSONB array

Revision ID: 0416e7cafa7b
Revises: 5822f3527585
Create Date: 2025-07-24 18:48:36.565949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0416e7cafa7b'
down_revision: Union[str, Sequence[str], None] = '5822f3527585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('has_alt_text', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_posts_has_alt_text'), 'posts', ['has_alt_text'], unique=False)
    op.create_index('ix_posts_images_gin', 'posts', ['images'], unique=False, postgresql_using='gin')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_posts_images_gin', table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('ix_posts_has_alt_text'), table_name='posts')
    op.drop_column('posts', 'images')
    op.drop_column('posts', 'has_alt_text')
    # ### end Alembic commands ###
