"""Add GIN indexes to posts table

Revision ID: 1c3203a5fd8d
Revises: 74a5ca96896c
Create Date: 2025-07-23 02:35:47.185958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3203a5fd8d'
down_revision: Union[str, Sequence[str], None] = '74a5ca96896c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_embeds_gin', 'posts', ['embeds'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_facets_gin', 'posts', ['facets'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_links_gin', 'posts', ['links'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_links_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_facets_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_embeds_gin', table_name='posts', postgresql_using='gin')
    # ### end Alembic commands ###
