"""Add is_active flag to achievements

Revision ID: 485096d371eb
Revises: a3fc2df55656
Create Date: 2025-07-27 05:23:39.960551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485096d371eb'
down_revision: Union[str, Sequence[str], None] = 'a3fc2df55656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_achievements_is_active'), 'achievements', ['is_active'], unique=False)
    op.add_column('user_stats', sa.Column('image_post_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_stats', sa.Column('video_post_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'video_post_count')
    op.drop_column('user_stats', 'image_post_count')
    op.drop_index(op.f('ix_achievements_is_active'), table_name='achievements')
    op.drop_column('achievements', 'is_active')
    # ### end Alembic commands ###
