"""Add Bluesky feed metadata fields

Revision ID: 55fb776f6087
Revises: 58a5320d8060
Create Date: 2025-08-06 23:12:56.628241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fb776f6087'
down_revision: Union[str, Sequence[str], None] = '58a5320d8060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('feeds', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('bluesky_description', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('last_bluesky_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'last_bluesky_sync')
    op.drop_column('feeds', 'bluesky_description')
    op.drop_column('feeds', 'like_count')
    op.drop_column('feeds', 'avatar_url')
    # ### end Alembic commands ###
