"""Add unified media thumbnail and aspect ratio fields

Revision ID: 5822f3527585
Revises: 7606d24bce47
Create Date: 2025-07-24 16:39:19.293634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5822f3527585'
down_revision: Union[str, Sequence[str], None] = '7606d24bce47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('aspect_ratio_width', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('aspect_ratio_height', sa.Integer(), nullable=True))
    op.drop_column('posts', 'link_thumbnail_url')
    op.drop_column('posts', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('link_thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'aspect_ratio_height')
    op.drop_column('posts', 'aspect_ratio_width')
    op.drop_column('posts', 'thumbnail_url')
    # ### end Alembic commands ###
