"""Add order field to feeds table

Revision ID: 58a5320d8060
Revises: ddf1a70f0d36
Create Date: 2025-08-06 23:07:00.988586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a5320d8060'
down_revision: Union[str, Sequence[str], None] = 'ddf1a70f0d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'order')
    # ### end Alembic commands ###
