"""Add battle royale polling fields to Post model

Revision ID: 6272d95ed050
Revises: ee91efb30946
Create Date: 2025-07-01 21:15:36.302830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6272d95ed050'
down_revision: Union[str, Sequence[str], None] = 'ee91efb30946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('is_active_for_polling', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_is_active_for_polling'), 'posts', ['is_active_for_polling'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_is_active_for_polling'), table_name='posts')
    op.drop_column('posts', 'is_active_for_polling')
    op.drop_column('posts', 'last_polled_at')
    # ### end Alembic commands ###
