"""Add GIN indexes to posts table

Revision ID: 74a5ca96896c
Revises: da92c5650639
Create Date: 2025-07-23 01:34:12.623690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a5ca96896c'
down_revision: Union[str, Sequence[str], None] = 'da92c5650639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_engagement_score'), 'posts', ['engagement_score'], unique=False)
    op.create_index('ix_posts_hashtags_gin', 'posts', ['hashtags'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_mentions_gin', 'posts', ['mentions'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_mentions_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_hashtags_gin', table_name='posts', postgresql_using='gin')
    op.drop_index(op.f('ix_posts_engagement_score'), table_name='posts')
    # ### end Alembic commands ###
