"""Add GIN indexes for embeds, facets, and links

Revision ID: 7606d24bce47
Revises: 1c3203a5fd8d
Create Date: 2025-07-23 02:36:43.534304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7606d24bce47'
down_revision: Union[str, Sequence[str], None] = '1c3203a5fd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
