"""Add admin system models - API keys and feed applications

Revision ID: 7684af04df73
Revises: 55fb776f6087
Create Date: 2025-08-08 00:21:09.276166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7684af04df73'
down_revision: Union[str, Sequence[str], None] = '55fb776f6087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.Enum('MASTER_ADMIN', 'FEED_OWNER', name='apikeytype'), nullable=False),
    sa.Column('owner_did', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_owner_did'), 'api_keys', ['owner_did'], unique=False)
    op.create_table('feed_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_did', sa.String(length=255), nullable=False),
    sa.Column('feed_id', sa.String(length=255), nullable=False),
    sa.Column('websocket_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_applications_applicant_did'), 'feed_applications', ['applicant_did'], unique=False)
    op.add_column('feeds', sa.Column('owner_did', sa.String(length=255), nullable=True))
    # Add is_active with default value for existing rows
    op.add_column('feeds', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # Update tier column to have default and make NOT NULL
    op.execute("UPDATE feeds SET tier = 'bronze' WHERE tier IS NULL")
    op.alter_column('feeds', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               server_default='bronze')
    op.create_index(op.f('ix_feeds_owner_did'), 'feeds', ['owner_did'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_owner_did'), table_name='feeds')
    op.alter_column('feeds', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               server_default=None)
    op.drop_column('feeds', 'is_active')
    op.drop_column('feeds', 'owner_did')
    op.drop_index(op.f('ix_feed_applications_applicant_did'), table_name='feed_applications')
    op.drop_table('feed_applications')
    op.drop_index(op.f('ix_api_keys_owner_did'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
