"""add_configuration_tables_geo_hashtags_and_news_domains

Revision ID: 8493bedcb492
Revises: d5756894a8b6
Create Date: 2025-08-08 05:27:33.184624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8493bedcb492'
down_revision: Union[str, Sequence[str], None] = 'd5756894a8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_hashtag_mappings',
    sa.Column('hashtag', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('hashtag')
    )
    op.create_index(op.f('ix_geo_hashtag_mappings_country'), 'geo_hashtag_mappings', ['country'], unique=False)
    op.create_index(op.f('ix_geo_hashtag_mappings_hashtag'), 'geo_hashtag_mappings', ['hashtag'], unique=False)
    op.create_table('news_domains',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_news_domains_domain'), 'news_domains', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_domains_domain'), table_name='news_domains')
    op.drop_table('news_domains')
    op.drop_index(op.f('ix_geo_hashtag_mappings_hashtag'), table_name='geo_hashtag_mappings')
    op.drop_index(op.f('ix_geo_hashtag_mappings_country'), table_name='geo_hashtag_mappings')
    op.drop_table('geo_hashtag_mappings')
    # ### end Alembic commands ###
