"""COMMENT HERE

Revision ID: 8816843da6bb
Revises: fc331aa14077
Create Date: 2025-07-18 18:14:16.013786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8816843da6bb'
down_revision: Union[str, Sequence[str], None] = 'fc331aa14077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_post_feed_uc', 'feed_posts', ['post_id', 'feed_id'])
    op.create_index('idx_feed_posts_feed_ingested', 'feed_posts', ['feed_id', 'ingested_at'], unique=False)
    op.create_index('idx_feed_posts_post_ingested', 'feed_posts', ['post_id', 'ingested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feed_posts_post_ingested', table_name='feed_posts')
    op.drop_index('idx_feed_posts_feed_ingested', table_name='feed_posts')
    op.drop_constraint('_post_feed_uc', 'feed_posts', type_='unique')
    # ### end Alembic commands ###
