"""Add contrails_websocket_url to feeds table

Revision ID: a0854db1739e
Revises: 6272d95ed050
Create Date: 2025-07-02 20:29:00.501151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0854db1739e'
down_revision: Union[str, Sequence[str], None] = '6272d95ed050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('contrails_websocket_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('engagement_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'engagement_score')
    op.drop_column('feeds', 'contrails_websocket_url')
    # ### end Alembic commands ###
