"""achievement-per-feed

Revision ID: a3fc2df55656
Revises: a02cf75038a1
Create Date: 2025-07-27 03:49:06.198988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fc2df55656'
down_revision: Union[str, Sequence[str], None] = 'a02cf75038a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_feed_rarity',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.String(length=255), nullable=False),
    sa.Column('rarity_percentage', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('achievement_id', 'feed_id')
    )
    op.create_index(op.f('ix_posts_next_poll_at'), 'posts', ['next_poll_at'], unique=False)
    op.create_index('ix_posts_polling_queue', 'posts', ['is_active_for_polling', 'next_poll_at'], unique=False)
    op.create_foreign_key(None, 'user_achievements', 'feeds', ['feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_index('ix_posts_polling_queue', table_name='posts')
    op.drop_index(op.f('ix_posts_next_poll_at'), table_name='posts')
    op.drop_table('achievement_feed_rarity')
    # ### end Alembic commands ###
