"""Add created_at to Aggregate table

Revision ID: a81d47cfa51b
Revises: a0854db1739e
Create Date: 2025-07-10 17:07:34.977987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81d47cfa51b'
down_revision: Union[str, Sequence[str], None] = 'a0854db1739e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregates', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregates', 'created_at')
    # ### end Alembic commands ###
