"""series key

Revision ID: b347205567af
Revises: b4d2c6f693a1
Create Date: 2025-07-27 19:47:11.968314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b347205567af'
down_revision: Union[str, Sequence[str], None] = 'b4d2c6f693a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('series_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_achievements_series_key'), 'achievements', ['series_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_achievements_series_key'), table_name='achievements')
    op.drop_column('achievements', 'series_key')
    # ### end Alembic commands ###
