"""Add indexes for stats worker performance

Revision ID: b4d2c6f693a1
Revises: c82f618f3222
Create Date: 2025-07-27 18:49:52.675906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d2c6f693a1'
down_revision: Union[str, Sequence[str], None] = 'c82f618f3222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feed_posts_feed_id'), 'feed_posts', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_posts_post_id'), 'feed_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_author_did'), 'posts', ['author_did'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_did'), table_name='posts')
    op.drop_index(op.f('ix_feed_posts_post_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_feed_id'), table_name='feed_posts')
    # ### end Alembic commands ###
