"""Add max_post_engagement to user_stats

Revision ID: c82f618f3222
Revises: d2a07da4e841
Create Date: 2025-07-27 06:28:21.753855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82f618f3222'
down_revision: Union[str, Sequence[str], None] = 'd2a07da4e841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('max_post_engagement', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'max_post_engagement')
    # ### end Alembic commands ###
