"""Initial migration

Revision ID: d493c0964626
Revises: 
Create Date: 2025-06-28 22:14:26.314281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd493c0964626'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.String(length=255), nullable=False),
    sa.Column('agg_name', sa.String(length=255), nullable=False),
    sa.Column('timeframe', sa.String(length=50), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('did', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_index(op.f('ix_users_did'), 'users', ['did'], unique=False)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=False),
    sa.Column('cid', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_did', sa.String(length=255), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('has_link', sa.Boolean(), nullable=True),
    sa.Column('has_quote', sa.Boolean(), nullable=True),
    sa.Column('has_mention', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('link_title', sa.String(), nullable=True),
    sa.Column('link_description', sa.Text(), nullable=True),
    sa.Column('link_thumbnail_url', sa.String(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('embeds', sa.JSON(), nullable=True),
    sa.Column('raw_record', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['author_did'], ['users.did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cid')
    )
    op.create_index(op.f('ix_posts_uri'), 'posts', ['uri'], unique=True)
    op.create_table('feed_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.String(length=255), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_posts')
    op.drop_index(op.f('ix_posts_uri'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_did'), table_name='users')
    op.drop_table('users')
    op.drop_table('aggregates')
    # ### end Alembic commands ###
