"""Add applicant_handle to feed_applications

Revision ID: d5756894a8b6
Revises: 7684af04df73
Create Date: 2025-08-08 01:44:22.156141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5756894a8b6'
down_revision: Union[str, Sequence[str], None] = '7684af04df73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_applications', sa.Column('applicant_handle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_applications', 'applicant_handle')
    # ### end Alembic commands ###
