"""Add rarity tier and label to achievements

Revision ID: ddf1a70f0d36
Revises: b347205567af
Create Date: 2025-07-29 23:10:11.554669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf1a70f0d36'
down_revision: Union[str, Sequence[str], None] = 'b347205567af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_feed_rarity', sa.Column('rarity_tier', sa.String(), nullable=True))
    op.add_column('achievement_feed_rarity', sa.Column('rarity_label', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('rarity_tier', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('rarity_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'rarity_label')
    op.drop_column('achievements', 'rarity_tier')
    op.drop_column('achievement_feed_rarity', 'rarity_label')
    op.drop_column('achievement_feed_rarity', 'rarity_tier')
    # ### end Alembic commands ###
