"""Add video and quoted post fields, update user/feed models

Revision ID: ee91efb30946
Revises: f8f000b463f0
Create Date: 2025-07-01 16:49:00.974149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee91efb30946'
down_revision: Union[str, Sequence[str], None] = 'f8f000b463f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contrails_websocket_base_url', sa.String(), nullable=True),
    sa.Column('bluesky_at_uri', sa.String(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('last_aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_id'), 'feeds', ['id'], unique=False)
    op.create_foreign_key(None, 'aggregates', 'feeds', ['feed_id'], ['id'])
    op.add_column('feed_posts', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feed_posts', 'feeds', ['feed_id'], ['id'])
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('repost_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('reply_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('quote_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('last_engagement_poll_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('link_url', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_uri', sa.String(length=512), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_cid', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_author_did', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_author_handle', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_author_display_name', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_text', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_like_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_repost_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_reply_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('quoted_post_created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('posts_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_prominent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_prominent_refresh_check', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_prominent_refresh_check')
    op.drop_column('users', 'is_prominent')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'posts_count')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('posts', 'quoted_post_created_at')
    op.drop_column('posts', 'quoted_post_reply_count')
    op.drop_column('posts', 'quoted_post_repost_count')
    op.drop_column('posts', 'quoted_post_like_count')
    op.drop_column('posts', 'quoted_post_text')
    op.drop_column('posts', 'quoted_post_author_display_name')
    op.drop_column('posts', 'quoted_post_author_handle')
    op.drop_column('posts', 'quoted_post_author_did')
    op.drop_column('posts', 'quoted_post_cid')
    op.drop_column('posts', 'quoted_post_uri')
    op.drop_column('posts', 'link_url')
    op.drop_column('posts', 'video_url')
    op.drop_column('posts', 'last_engagement_poll_timestamp')
    op.drop_column('posts', 'quote_count')
    op.drop_column('posts', 'reply_count')
    op.drop_column('posts', 'repost_count')
    op.drop_column('posts', 'like_count')
    op.drop_constraint(None, 'feed_posts', type_='foreignkey')
    op.drop_column('feed_posts', 'relevance_score')
    op.drop_constraint(None, 'aggregates', type_='foreignkey')
    op.drop_index(op.f('ix_feeds_id'), table_name='feeds')
    op.drop_table('feeds')
    # ### end Alembic commands ###
