"""Add unique constraint to Aggregate model

Revision ID: fc331aa14077
Revises: e1baf30aba24
Create Date: 2025-07-17 16:56:42.603911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc331aa14077'
down_revision: Union[str, Sequence[str], None] = 'e1baf30aba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_feed_agg_timeframe_uc', 'aggregates', ['feed_id', 'agg_name', 'timeframe'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_feed_agg_timeframe_uc', 'aggregates', type_='unique')
    # ### end Alembic commands ###
